### ISSUE TITLE
Atom crash after narrow:search

### ISSUE THREAD

**Issue by kdnk** [t9md/atom-narrow#239] opened 2017-08-14 12:14 UTC
When I search some word by `narrow:search` and I move cursor to bottom in `narrow-editor`, Atom always freeze up like following gif(only vim-mode-plus & atom-narrow is activated).

![kapture 2017-08-14 at 21 07 20](https://user-images.githubusercontent.com/15260226/29271064-9cfd040e-8134-11e7-8eeb-37fa34d720d3.gif)

I can't see console so this might not be caused by narrow.
Have you ever seen like this crash and do you know why this caused?

Thanks!

Atom: 1.19.0
vim-mode-plus: 0.96.2
atom-narrow: 0.50.3

**Comment by t9md** [comment] 2017-08-15 08:17
I can't reproduce and haven't experienced that.

What your OS?

What is your narrow config?

Do you tune key-repeat rate via Karabiner or similar software?

In your GIF, why auto-preview is not happen while you are moving down, because of too fast or you explicitly disable it?

**Comment by kdnk** [comment] 2017-08-15 09:19
I use macOS 10.12.6.

My narrow config is following.
```
  narrow:
    Search:
      autoPreview: false
      autoPreviewOnQueryChange: false
      revealOnStartCondition: "always"
    directionToOpen: "down:always-new-pane"
    queryCurrentWordByDoubleClick: false
```
I turn off auto-preview only for `narrow:search`.

I tune key-repeat rate via System Preferences, not using like Karabiner.

**Comment by t9md** [comment] 2017-08-15 09:25
how is the rate? I want to reproduce to fix it.

**Comment by kdnk** [comment] 2017-08-15 09:27
My key repeat settings.
<img width="665" alt="screenshot" src="https://user-images.githubusercontent.com/15260226/29310071-5b27c38a-81e7-11e7-83c0-dc516e1aaca1.png">

**Comment by t9md** [comment] 2017-08-15 09:38
I tried with your config and same keyrepeat setting, but couldn't reproduce.

I use narrow with vim-mode-plus enabled but have no freeze issue.

Can you find minimum set of package combination to reproduce.

**Comment by t9md** [comment] 2017-08-15 09:48
And what is your keystroke to move down, `j` ? `ctrl-n`?
Does that happen in small code base?

Ideally I want full set of codebase/keystroke on each step to reproduce issue.

**Comment by kdnk** [comment] 2017-08-15 10:38
I can produce this issue only enabling narrow.
I used `j` to move down in the gif above.

In following gif, I produce this issue.

![kapture 2017-08-15 at 19 32 01](https://user-images.githubusercontent.com/15260226/29312497-8a5149de-81f0-11e7-9d9b-fe0320bf60aa.gif)

Codebase is here. https://github.com/kdnk/dotfiles
And my atom setting is here https://github.com/kdnk/dotfiles/tree/master/atom
I hope it might help you.
In the gif, I use Atom 1.19.1 only activate narrow and the other packages is disabled.

Following is the step I produce this.
- Open my dotfile directory in Atom by `atom .` command.
- Open command pallte by `cmd+shift+p` and put `enter` to confirm `narrow:search`
- Put statement `vim-mode-plus`  to `narrow-editor` and scroll to the bottom by `down` key.
- Then curor move to the bottom, always atom is crushed.

**Comment by t9md** [comment] 2017-08-15 12:37
Let me clarify, you can reproduce 1. "with atom +narrow  only" or 2. "atom +narrow +vim-mode-plus"?
Which is your situation 1 or 2?

**Comment by t9md** [comment] 2017-08-15 13:07
After i read again i understand vmp is not necessary to repro.
Will try to reproduce later.

**Comment by t9md** [comment] 2017-08-15 13:49
I couldn't repro with your dot file and codebase, so what I can do next is to use your atom config.
But I also want you to narrow down condition further.

Since might not common issue where every user hit.

You can reproduce issue with older narrow?
You find any common condition when editor stops like "always stops when cursor reached to line which is one line before last line" or something.

Anyway my motivation to reproduce issue is getting decrease, I want to try it again after concrete reproduce steps was settled.

**Comment by t9md** [comment] 2017-08-15 13:53
OK, I can repro using your config :tada:
Investigate it from now.

**Comment by t9md** [comment] 2017-08-15 14:27
Still not clear if it's Atom-core issue or narrow issue, I thinks I found config to avoid freezing.

Can you check issue resolved by checking "Scroll Past End" editor config.
By enabling this I no longer see issue. That's why I couldn't reproduce.

<img width="789" alt="settings_ ___github_work_dotfiles" src="https://user-images.githubusercontent.com/155205/29320038-f7abf0ae-8210-11e7-9fc8-bf5427ff72dc.png">

**Comment by kdnk** [comment] 2017-08-15 15:06
I checked "Scroll Past End", narrow works!!!🤣
Thanks so much!!!!!

**Comment by t9md** [comment] 2017-08-15 15:23
Can you remember this was not happened in Atom v1.18.0 then after updating to Atom v1.19.0, issue started?
If so, this might be Atom-core's bug, v1.19.0 includes tons of rewritten for editor-rendering logic.
Why I say this is I **could** reproduce issue with older version of narrow v0.49.0.

**Comment by kdnk** [comment] 2017-08-15 15:44
This issue happened after I updated to Atom v1.19.0.
But for these two months, I used v1.19.0-beta, I also remember this issue was not happened.

**Comment by t9md** [comment] 2017-08-15 15:45
Thanks.

**Closed** 2017-08-16 15:46 UTC
Labels: bug
